server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway         #这是注册进入Eureka唯一的微服务的名字
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
zuul: 
  #ignored-services: microservicecloud-dept
  ignored-services: "*"
  prefix: /xiaosha
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    
info:
  app.name: learn-microservicecloud
  app.author: xiaosha
  app.info: microservicecloud-zuul-gateway-9527路由网关
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  

  #ignored-services: microservicecloud-dept
  #prefix: /atguigu
  #ignored-services: "*"